hmcts/et-pet-et1

app/presenters/confirmation_email_presenter.rb, app/presenters/confirmation_presenter.rb, app/services/jadu/claim.rb, app/views/claim_confirmations/show.html.slim, config/locales/claim_confirmation.en.yml, spec/factories.rb, spec/features/confirmation_page_spec.rb, spec/features/session_expiry_spec.rb, spec/features/xml_generation_spec.rb, spec/models/jadu_xml/document_id_spec.rb, spec/presenters/confirmation_presenter_spec.rb, spec/rails_helper.rb
Show different copy for different application states, e.g. remission,
normal, partial remission, payment failure, etc.
=> Confirmation page permutations

spec/mailer_previews/confirmation_email_preview.rb
Arity change fixes mailer previews. 
We also pass multiple traits to FG in order to ensure PDF is available. PDF generation was removed from the mailers.
=> Mailer Previews Fix: Confirmation Email Arity Change

app/validators/post_code_validator.rb, config/locales/en.yml, spec/forms/additional_claimants_form/additional_claimant_spec.rb, spec/forms/additional_respondents_form/additional_respondent_spec.rb, spec/forms/claimant_form_spec.rb, spec/forms/representative_form_spec.rb, spec/forms/respondent_form_spec.rb, spec/support/shared_examples/postcode_validation.rb
=> Allows contextual lookup when using i18n with error messages for postcode validations

app/views/layouts/application.html.slim
cookie message was getting rendered before the doctype. Chrome is forgiving, but I wouldn't put it past IE to go all bonkers over it.
=> moved cookie message to somewhere sensible

app/presenters/jadu_xml/acas_presenter.rb, spec/presenters/jadu_xml/acas_presenter_spec.rb
The mapping for security services had been changed and didn't match
up with the presenter. Fixed and added a regression test to catch
in the future.
=> Fix AcasPresenter

lib/tasks/sneakers.rake
If there's an error, the message goes into the -retry queue, retries are managed by sneakers. If the max retries fail the message is sent to the -error queue.
=> Setup deadletter queue

app/models/respondent.rb, spec/models/respondent_spec.rb
FGR requests should only be made by the primary respondent. The
request code was written before multiple repsondents was implemented.
This commit ensures FGR requests are only made by the primary
respondent.
=> Fix fee group reference request behaviour

app/models/claim.rb, spec/features/save_and_return_spec.rb
fixes #579 
*shoulda matcher perfoms valid `authenticates` checks with the `have_secure_password` matcher hence no test added or changed in the claim spec
=> Check memorable word is present before trying to authenticate

Gemfile
We need it for env specific .env files. Can't wait til we don't have to use this anymore.
=> Lock Dotenv at earlier version

Gemfile, Gemfile.lock, app/admin/claim.rb, app/assets/javascripts/active_admin.js.coffee, app/assets/stylesheets/active_admin.css.scss, config/initializers/active_admin.rb, config/routes.rb, db/migrate/20150128174612_create_active_admin_comments.rb, db/schema.rb
Couple of things:
- There are no user accounts, anyone on the VPN can access this page. It's a 404 if they're not on the VPM.
- Pending the addition of user accounts the ability to change or otherwise interfere with claims is disabled.
- Similarly it is not possible to view any claimant or claim information, just metadata.
=> Admin dashboard for inflight metadata inspection

app/assets/stylesheets/forms/_form-errors.scss, app/form_builder/et_fees/error_notification.rb, app/views/shared/_error_notification.html.slim, app/views/user_sessions/new.html.slim, config/locales/en.yml
At this point we only use this on the user sessions page. The behaviour
is if there are errors on base show the errors in the notification
header, else show the fix errors below message.
=> Render errors on base

app/jobs/pdf_generation_job.rb, app/models/claim.rb, app/models/claim/finite_state_machine.rb, spec/jobs/pdf_generation_job_spec.rb, spec/models/claim_spec.rb
=> Allow pdf to be generated when payment is required

Gemfile, Gemfile.lock
Uses this gem:
https://github.com/alexspeller/non-stupid-digest-assets
To fix this issue:
https://github.com/rails/sprockets-rails/issues/49
@dan-palmer I think this is the best solution, it seems to create a copy which is better than symlinking if we end up hosting the assets somewhere else.
=> Compile non digested assets

package.sh
The docker push stuff at the end we want to carry on to remove images so
the jenkins server doesn't bloat.
=> Wrap most of the package script in `set -e` to stop on error

app/models/claim.rb, app/presenters/jadu_xml/claim_presenter.rb, app/services/claim_fee_calculator.rb, spec/models/claim_spec.rb, spec/presenters/jadu_xml/claim_presenter_spec.rb, spec/services/claim_fee_calculator_spec.rb
Whistleblowing claims should attract the higher fee.
Renames Claim#alleges_discrimination_or_unfair_dismissal? to
Claim#attracts_higher_fee? and updates the logic of this method to
reflect the above.
=> Blowing whistles is pricey

app/views/base_mailer/access_details_email.en.text.erb, app/views/base_mailer/confirmation_email.text.erb, app/views/base_mailer/shared/_footer.html.slim, config/locales/mailers.en.yml
We decided that having this doesn't help as any scammers could just remove this or change the email address, and it seems that users are hitting reply-to-all and getting emails to this list.
I have no idea if this will pas its tests as I don't know how/what to set the missing env vars too (`key not found: "EPDQ_PSPID" (KeyError)` for starters)
=> Remove security/phishing from email footers

app/helpers/signout_visibility_helper.rb, spec/features/multiple_claimants_spec.rb
The signout helper now supports the the `update` action when requests go through the multiples controller
=> Ensure save & complete later is visible when adding more claimants manually

app/forms/additional_information_form.rb, app/forms/claim_details_form.rb, app/models/claim.rb, app/presenters/additional_information_presenter.rb, app/presenters/claim_details_presenter.rb, app/presenters/confirmation_presenter.rb, app/views/claims/_additional_information.html.slim, app/views/claims/_claim_details.html.slim, config/locales/claim_review.en.yml, config/locales/en.yml, db/migrate/20150212171232_rename_additional_information_rtf_to_claim_details_rtf_on_claim.rb, db/schema.rb, spec/factories.rb, spec/features/attaching_a_document_spec.rb, spec/forms/additional_information_form_spec.rb, spec/forms/claim_details_form_spec.rb, spec/models/claim_spec.rb, spec/presenters/additional_information_presenter_spec.rb, spec/presenters/claim_details_presenter_spec.rb, spec/presenters/jadu_xml/file_presenter_spec.rb, spec/services/jadu/claim_spec.rb
This renames the column on the claims table, because of this it will also mean we have to re-sync the files in S3. I just didn't want to have the uploader called additional_information_rtf & still have the additional_information_form.
Updated with new designs(Monday 9th March)
=> Move additional information rtf upload to claim details page

Gemfile, Gemfile.lock, app/forms/application_number_form.rb, app/forms/representative_form.rb, config/locales/en.yml, spec/forms/application_number_form_spec.rb, spec/forms/representative_form_spec.rb, spec/support/shared_examples/email_validation.rb
This adds email validation to the user's and representitives' email addresses. This is mostly to ensure that no spaces are entered in the email address as it causes ActionMailer to blow up.
=> Email validation

app/forms/additional_information_form.rb, app/forms/claim_details_form.rb, config/locales/en.yml, spec/forms/additional_information_form_spec.rb, spec/forms/claim_details_form_spec.rb
This reduces the maximum number of characters for claim details and additional information. This should prevent truncation of these fields in the fixed space of the PDF boxes.
=> Shorter strings for pdf fields.

app/presenters/jadu_xml/address_properties.rb, spec/factories.rb, spec/features/claim_xml_generation_spec.rb
Ensure that respondents with empty work addresses validates correctly against V0.24 of the Jadu Schema when represented as XML.
=> Render empty respondents work address in XML

app/validators/date_validator.rb, spec/support/shared_examples/date.rb
Adds a check to ensure the year is greater than 1000 so as to guarantee the user provided 4 digits. This stops users creating dates in the format dd/mm/yy - which is now necessary as Jadu require a date of birth to be passed in the xml.
=> Improved Year Validation For Date Fields

app/helpers/claim_reviews_helper.rb, app/models/claim.rb, spec/features/create_claim_applications_spec.rb, spec/support/form_methods.rb
Prior to this PR - a group with partial remission showed the button text that a full remission claim would have. 
The cause of this was due to the method for presenting the button text checked only remission had been applied - it now checks the remission count instead.
=> Submit Claim Button Text Fix For Group Claims

app/presenters/confirmation_presenter.rb, config/locales/claim_confirmation.en.yml, spec/presenters/confirmation_presenter_spec.rb
Adds the text 'None' if no files are present, else the file names are presented instead.
Fixes #678
=> Explicitly state that no attachments are present on the confirmation page/email

app/assets/javascripts/application.js, app/assets/javascripts/modules/moj.aria-alert.js
Somehow Aria JS was removed, this is why screenreaders never read out the error.
=> fixes #708.

config/initializers/amqp.rb, config/unicorn.rb, docker/rails/unicorn.service
This makes it possible to define the number of worker processess for
sneakers and unicorn through environment variables.
Also move to parsing integers with the Integer class rather than .to_i
which is safer because it throws an exception if given a string as
input.
=> Make workers configurable

app/forms/claimant_form.rb, spec/forms/claimant_form_spec.rb
PDF filenames can no longer have spaces in them as first and last names values are now 'stripped' before being persisted.
Fixes #707
=> Strips whitespace from the primary claimants first & last name

app/controllers/user_sessions_controller.rb, spec/features/save_and_return_spec.rb, spec/features/session_expiry_spec.rb, spec/support/time_helper.rb
Hitting the user sessions controller would reset the session expires_in value thus keeping the session alive. 
This fix ensures the action that sets the sessions expires_in time is not executed when a user hits the expiry page.
=> Ensure a user cannot re-enter the form once session has expired

app/helpers/claim_reviews_helper.rb, app/presenters/confirmation_email_addresses_presenter.rb, app/views/claim_reviews/_email_addresses.html.slim, spec/presenters/confirmation_email_addresses_presenter_spec.rb
Presenter that returns a list of emails & determines the checked properties of the emails based on which emails are present in the claim.
Fixes #737
=> Adds a presenter for confirmation email addresses on review page

app/controllers/payments_controller.rb, app/models/event.rb, app/services/payment_gateway/response.rb, config/locales/barclaycard_gateway.en.yml, spec/controllers/payments_controller_spec.rb, spec/services/payment_gateway/response_spec.rb
Assigns an event to a claim for instances when barclaycard cannot guarantee at the time a user submits payment whether the payment has actually been authorised.
=> Log events when the status of a successful barclaycard callback is uncertain

spec/features/quick_edit_spec.rb
Uses a factory girl pre configured claim rather than fill in each page in the app to hit the review page.
Speed improvement: 17-16 secs => 4-5 secs.
=> Speed up quick edit spec

config/initializers/amqp.rb, docker/rails/Dockerfile, docker/rails/logstash-conf.sh, docker/rails/sneakers.logger
Get sneakers to log to STDOUT and then capture the log using the init
system. Trying this because otherwise sneakers rotates its own log file
and occassionally breaks the shipping.
=> Set sneakers to log to STDOUT

app/services/representative_type.rb, spec/services/representative_type_spec.rb
Trade Association was spelt incorrectly & as it is validated against the
schema it can cause claims to fail validation and not be sent through to
Jadu.
=> Correct RepresentativeType spelling error

.travis.yml
Should be able to benefit from faster build start times along with
faster builds by updating the config to use addon->packages
configuration option for pdftk.
See: http://docs.travis-ci.com/user/migrating-from-legacy/
=> Use Travis CI container infrastructure

config/initializers/amqp.rb, lib/tasks/sneakers.rake
There used to be heartbeat timeouts during workload and initial
handshake in the rabbitmq. This manifested to issues where ActiveJobs
were not being enqueued properly into rabbitmq, for example claims were
being marked as submitted while never having made it into the queues.
Adding the changes just to `config/initializers/amqp.rb` was not enough 
as reconfiguring the heartbeat timeout happens early during handshake
so it was picking the 2 second default timeout specified by sneakers.
Problem details
----------
During a heartbeat definition of 28 seconds, two heartbeats will be sent in the total of 28 seconds and the responses must have been retrieved. This number is configurable on both server side and client side, and during the connection handshake this is negotiated on both sides so …
=> Fixes rabbitmq heartbeat timeouts

app/models/claim.rb, app/services/payment_gateway.rb
Adds logging to the payment gateway when the state changes from
available = true to false and vice versa. This should allow someone
to detect whether the gateway ever becomes unavailable
(spoiler alert: it does become unavailable often).
=> Add payment gateway task logging

app/views/claims/_your_fee.html.slim, app/views/guides/markdown/reducing_fees.md, config/locales/claim_confirmation.en.yml, config/locales/mailers.en.yml, spec/features/confirmation_page_spec.rb, spec/features/create_claim_applications_spec.rb, spec/mailers/base_mailer_spec.rb
Also, changing some instance of ‘fee remission’ to the new product name
‘ help with fees’
=> Updating links to help with fees info

app/views/claim_confirmations/show.html.slim, app/views/claims/_your_fee.html.slim, app/views/guides/markdown/reducing_fees.md, config/locales/claim_confirmation.en.yml, config/locales/mailers.en.yml, spec/features/confirmation_page_spec.rb, spec/mailers/base_mailer_spec.rb
The content was updated, but the old URL was left in.
This change fixes that.
=> Fix for a old link

lib/tasks/sidekiq_stats.rake
The task will be cron'd so that sidekiq status info
can be logged and shipped to kibana.
bundle exec rake sidekiq_stats >> /var/log/sidekiq_log.json
=> Add basic rake task to report sidekiq queue status

app/presenters/claim_type_presenter.rb, app/views/claims/_additional_claimants_upload.html.slim, config/locales/claim_review.en.yml, spec/presenters/claim_type_presenter_spec.rb
If a user selects protetive award this option now appears on the claim
review page
Also fixed the additional claimants csv download link.
=> Get protective award opt. to appear on review page

lib/tasks/sidekiq_stats.rake
The rake task that retrieves sidekiq stats now reports the number of ET
claims that have not been successfully submitted to Jadu
=> Add enqueued submission count to sidekiq stats

config/application.rb, spec/features/claim_xml_generation_spec.rb, spec/presenters/pdf_form/base_delegator_spec.rb
The app is not timezone aware, so in BST the times are still shown to be UTC.
These changes make the app TZ aware.  However, they also alter the date format presented to Jadu, so it's important enough testing is done to confirm that Jadu and underlying services such as CGI support this format.  If not, then some amends will be required to to apply the timezone offset but present a UTC date and time to external services.
=> Make app GMT/BST timezone aware

app/admin/claim.rb, app/models/event.rb, spec/features/admin_panel/admin_show_feature_spec.rb
We have situations where a claim may need to be manually resubmitted to
jadu, or simply marked as submitted (to silence alerts).
Two buttons have been added to the admin screen - one to resubmit a
claim and another to mark a claim as submitted.  In both instances an event
is recorded against the claim to indicate that the action was triggered
by an admin user.
=> Add submit buttons to admin

app/presenters/claim_type_presenter.rb, db/schema.rb, spec/presenters/claim_type_presenter_spec.rb
The protective award option shows as seleted on the claim review page
even if not selected by the user. This commit fixes that bug.
=> Fix protective_award display on claim review page

Gemfile, Gemfile.lock, spec/features/admin_panel/admin_show_feature_spec.rb, spec/models/claim_spec.rb, spec/models/stats/claim_stats_spec.rb
Four tests were failing because of a change of the default ordering of
the Event model. This commit fixes those tests.
=> Fix failing tests due to change of event ordering

.rspec, Gemfile, Gemfile.lock, app/forms/claim_type_form.rb, config/locales/en.yml, db/schema.rb, spec/features/claim_xml_generation_spec.rb, spec/forms/additional_claimants_form_spec.rb, spec/forms/claim_type_form_spec.rb, spec/models/claim_spec.rb, spec/models/stats/claim_stats_spec.rb, spec/rails_helper.rb
JIRA ticket: https://triadmoj.atlassian.net/browse/RST-12
As a public Employment Tribunal user, I want the system to make it mandatory to select at least one 'claim type', so I can comply with the Employment Tribunal Rules of Procedure for presenting a claim and the correct fee can be applied.
AC 1: The user cannot move to the next page without selecting at least one of the claim data types.
AC 2: Where a user proceeds without selecting a claim data type, system must present an error message.
AC3: Information from the form is stored in the Employment Tribunal database.
AC4: The correct fee has been applied to the ET application. Note: There are no changes required to the fee calculation.
=> Making sure that at least one claim type is submited.

app/views/claims/_claim_type.html.slim, spec/features/claim_type_page_spec.rb
JIRA ticket: https://triadmoj.atlassian.net/browse/RST-13
As a public Employment Tribunal user, I am required to select from a series of options what type of claim(s) I am making, I don’t’ need the words optional against specific types of claim.
AC 1: The text ‘optional’ must not appear against the ‘Unfair dismissal (including constructive dismissal)? option.
AC 2: The text ‘optional’ must not appear against the ‘Protective Award’ option.
AC3: The text ‘optional’ must not appear against the ‘Other claim type?’ option.
AC4: The text ‘optional’ must not appear against the Whistleblowing - ‘Are you reporting suspected wrongdoing at work? option.
AC5: The text ‘optional’ must not appear against the Whistleblowing – ‘Do you want us to send a copy of your claim to the relevant person or body …
=> I should not see text “optional” on claim type page.

app/controllers/payments_controller.rb, spec/controllers/payments_controller_spec.rb
We have an occasional issue when the payments are not accepted/processed. This should help us to find out why.
=> Raising sentry erro if payment not recognised, for debugging.

app/views/claim_reviews/_item.html.slim
I removed html_safe from presenter helper which then caused wrong rendering of string with <br> tags in. I add sanitising the string and allowing only BR tag so it's still safe.
=> Fixing formatting without html_safe.

app/forms/refunds/applicant_form.rb, app/forms/refunds/original_case_details_form.rb, app/views/refunds/_applicant.html.slim, app/views/refunds/_review.html.slim, config/locales/refunds.yml, db/migrate/20171127135309_rename_incorrect_fields_in_refunds.rb, db/schema.rb, features/step_definitions/refunds/review_steps.rb, features/support/page_objects/refund/review_page.rb, spec/factories.rb, spec/forms/refunds/applicant_form_spec.rb, spec/forms/refunds/original_case_details_form_spec.rb
This PR corrects an issue found by a user of the csv export who noticed only the applicant email existed - no claimant, but everywhere else, the applicants details were duplicated into the claimant (it was designed so that the applicant did not have to be the claimant)
This also highlighted that the email address names were inconsistent - it was not prefixed by the word 'applicant_' like everything else.
So, the following changes have been made in this PR
DB Changes (which will therefore affect the csv output)
what was applicant_email_address is now claimant_email_address
Claimant email address added to review page as it was missing previously
Added safe data migration to populate claimant_email_address of existing records
Improved unit test around the form objects for copying the data …
=> feature/rst-660 Populate Claimant Email Correctly

app/forms/refunds/applicant_form.rb, config/locales/refunds.yml, db/migrate/20171128092945_remove_is_claimant_from_refunds.rb, db/schema.rb, features/step_definitions/refunds/applicant_steps.rb, features/support/page_objects/refund/applicant_page.rb
A nice simple PR - to remove the is_claimant column from the database.  It used to be a question we asked on a form, but the question got removed and the database column didn't.
=> Removed is_claimant column from database - no longer required

config/database.yml
The db host is now configurable via the environment for use with docker setups using the 'local' environment.
=> The db host is now configurable via the environment

config/initializers/carrierwave.rb
Improvement to carrierwave config to allow the AWS endpoint and path_style options to be configurable from the environment.  This is for use with a fake s3 service in a docker environment for example.
Note that if these environment variables are not provided, the system operates exactly as it did before - assuming its own defaults etc...
=> Improvement to carrierwave config

app/helpers/diversities_helper.rb, app/views/diversities/_review.html.slim, spec/helpers/diversities_helper_spec.rb
When the religion value was free text it failed to display because there was no translation key that would match the value.
=> Fixing bug for free text religion value

app/views/claims/_additional_claimants_upload.html.slim, app/views/claims/_additional_information.html.slim, app/views/claims/_additional_respondents.html.slim, app/views/claims/_claim_details.html.slim, app/views/claims/_claim_type.html.slim, app/views/claims/_claimant.html.slim, app/views/claims/_employment.html.slim, app/views/claims/_representative.html.slim, app/views/claims/_respondent.slim, app/views/claims/_your_fee.html.slim, app/views/diversities/_age_caring.html.slim, app/views/diversities/_claim_type.html.slim, app/views/diversities/_disability.html.slim, app/views/diversities/_ethnicity.html.slim, app/views/diversities/_identity.html.slim, app/views/diversities/_pregnancy.html.slim, app/views/diversities/_relationship.html.slim, app/views/diversities/_religion.html.slim, app/views/refunds/_applicant.html.slim, app/views/refunds/_original_case_details.html.slim, app/views/refunds/_profile_selection.html.slim
This PR will do nothing right now - but I want it in before the rails 5 upgrade as it will switch off the hidden field which would otherwise get added to all radio buttons - meaning non selected values will be an empty string instead of nil.
In time, we can evaluate if we want it to use the rails 'norm' of an empty string of course
=> Added include_hidden: false to all radio buttons 

app/jobs/claim_submission_job.rb, spec/jobs/claim_submission_job_spec.rb
After the release of v3.0.0 it was found that the claim was not having its status set to submitted.
This fixes that bug
=> Now finalizing claim after submission to api

app/jobs/claim_submission_job.rb, spec/jobs/claim_submission_job_spec.rb
A bug was found when we did this release - the status of the claim was incorrect as the finalize! method was not being called on the claim.
* Now finalizing claim after submission to api
=> Now finalizing claim after submission to api (#939)

app/presenters/pdf_form/base_delegator.rb, spec/presenters/pdf_form/base_delegator_spec.rb
A bug was found where a postcode used by a user caused it to fail to generate the pdf.  The postcode was a weird one '1083' - but apparently, the postcode validator converts it to IO83 which is valid !!
Irrespective of whether we agree with that, the code should be robust enough to handle it if thinks its valid.
=> RST-1447 Claims in dead queue on sidekig

config/locales/cy/guides.cy.yml, config/locales/cy/terms.cy.yml, config/locales/en/guides.en.yml, config/locales/en/terms.en.yml, config/routes.rb, features/support/page_objects/refund/payment_details_page.rb, spec/controllers/feedback_controller_spec.rb, spec/features/create_claim_applications_spec.rb, spec/features/guide_spec.rb, spec/features/language_switch_spec.rb, spec/features/preventing_login_after_submission_spec.rb, spec/features/quick_edit_spec.rb, spec/features/request_redispatch_spec.rb, spec/features/session_expiry_spec.rb, spec/features/terms_spec.rb, spec/helpers/claims_helper_spec.rb
There is a requirement for a locale to be part of the URL. This is the PR that does just that. The url without locale in it will still work.
=> Fixing failing tests after locale moved to url

app/views/claims/_additional_claimants.html.slim, app/views/claims/_additional_respondents.html.slim
Fixed bug where the 'No' option of the 'Yes/No' selection for additional claimants and respondents page was being marked as read only - preventing it from being selected.  Luckily, it was selected by default.
=> Fixed bug where the 'No' option of the 'Yes/No' selection is readonly

Gemfile, config/boot.rb
Bootsnap is used to cache operations and increase boot time. This can make debugging initialisers a pain in the backside, so this PR moves bootsnap to prod only.
=> RST-1469: Bootsnap in Production Only

config/environments/production.rb
Rails production environment will now prevent flattening of pdf if the FLATTEN_PDF environment variable is set to "false"
=> Rails production environment will now prevent flattening of pdf in staging and dev

Gemfile.lock
=> RST-1521 ET1 - Upgrade rack to 2.0.6 or later due to vulnerability

config/environments/production.rb
RST-1757 ET1 (Azure) Asset configuration
This must not be deployed until ben has done his bit.  It is preparing for azure where we will correct the silly '/apply/assets' inconsistency in et1
Ben's ticket is https://tools.hmcts.net/jira/browse/RDO-3581
=> RST-1757 ET1 (Azure) Asset configuration

config/environments/production.rb
Bug fix to prevent redirect loop in diversity when running in production mode with no ssl (i.e. full system).  Now configurable by env var (default is as before)
=> Bug fix to prevent redirect loop in diversity

app/assets/stylesheets/_common.scss, app/helpers/maintenance_notice_helper.rb, app/views/layouts/application.html.slim, app/views/shared/_maintenance_notice.slim
When `SHOW_DOWNTIME_BANNER` environment variable is present, this PR ensures that a maintenance banner is shown on all service pages.
```
[ ] Yes
[x] No
```
=> RST-1884: Add maintenance notice when Env Var is present

app/helpers/maintenance_notice_helper.rb, config/locales/cy/cy.yml, config/locales/en/en.yml
Use I18n via the maintenance_notice helper method to translate the month and the string in its entirety
```
[ ] Yes
[x] No
```
=> Add Welsh to maintenance notice

config/environments/production.rb
This PR allows configuration of the raven client to allow SSL certificate verification to be disabled by setting RAVEN_SSL_VERIFICATION=false as an environment variable (defaults to true)
=> SSL Certificate Verification Control

app/views/api/claim/_build_primary_claimant.json.jbuilder, app/views/api/claim/_primary_claimant_attributes.json.jbuilder, spec/features/create_claim_applications_spec.rb, spec/support/api_support/json_objects/v2/build_primary_claimant_json_object.rb, spec/support/api_support/json_objects/v2/primary_claimant_json_object.rb, spec/support/form_methods.rb
This PR adds the selected value of the claimant country to the API as it is required by CCD
RST-1930
```
[ ] Yes
[X] No
```
Whilst this does change the API, it adds to it and the API is programmed to ignore anything it doesnt care about.
A version of the API is in another branch ready to take advantage of this data, but this PR can be merged and deployed independently
=> Rst 1930 add country to primary claimant

app/forms/claimant_form.rb, app/views/claims/_claimant.html.slim, config/initializers/simple_form.rb, features/output_form.feature, spec/forms/claimant_form_spec.rb
Reverts hmcts/et1#1120
This PR reverts the above ticket - a last minute change has been requested to remove the optional text - plus it is breaking the test suite as the email address question has lost its 'form-group' class which is important
=> Revert "RST-1124 Changed the radio buttons for the email address to show once clicked"

config/routes.rb
RST-2425
This PR (finally) fixes the issue where developers cannot create a database because there is no database - chicken and egg situation.
The workaround was to comment out 3 lines of code, create the db then uncomment them
```
[ ] Yes
[X] No
```
=> RST-2425 Solved problem with bitmask_attributes stopping rake db:create

app/forms/claim_type_form.rb, app/helpers/claim_reviews_helper.rb, app/models/claim.rb, app/views/claims/_claim_type.html.slim, config/locales/cy/claim_review.cy.yml, config/locales/cy/cy.yml, config/locales/en/claim_review.en.yml, config/locales/en/en.yml, spec/factories.rb, spec/features/claim_type_page_spec.rb, spec/forms/claim_type_form_spec.rb, spec/models/claim_spec.rb, spec/views/claim_reviews/show/review_page_claim_type_spec.rb
https://tools.hmcts.net/jira/browse/RST-2921
This PR removes the protective award section from the claim type page.  This field does not go to the API so no further changes needed.
```
[ ] Yes
[X] No
```
=> RST-2921 Remove Protective Award from 'About the claim' section

db/migrate/20210202120824_remove_is_protective_award_from_claims.rb, db/schema.rb
https://tools.hmcts.net/jira/browse/RST-3076
RST-3076 Removed is_protective_award from claims table - no longer used
```
[ ] Yes
[X] No
```
=> RST-3076 Removed is_protective_award from claims table - no longer used

app/forms/claimant_form.rb, app/validators/ccd_claimant_contact_preference_validator.rb, config/locales/cy/cy.yml, config/locales/en/en.yml, spec/validators/ccd_claimant_contact_preference_validator_spec.rb
Added the ccd contact preference validator spec + validator
```
[ ] Yes
[ X] No
```
=> RST-3153 ccd contact preference validator spec + validator added

app/views/diversities/index.html.slim
RST-2039
The start link on the diversity page is now a button
```
[ ] Yes
[ ] No
```
=> RST-2039 Changed start link on diversity page to a button

config/locales/en/et1/active_model.en.yml, spec/forms/respondent_form_spec.rb
Removed a letter for error message on Respondent detail's page 
```
[ ] Yes
[ X] No
```
=> RST-4036 removed content for error on respondent detail's page

app/forms/representative_form.rb, spec/forms/representative_form_spec.rb
Added before validation to clear the fields of contact reference depending on what the user selected also added the test for each different case. 
```
[ ] Yes
[X] No
```
=> RST-4275 Added before validation to clear field + Tests

app/services/validate_claimants_file_via_api_service.rb, app/validators/additional_claimants_csv_validator.rb, spec/validators/additional_claimants_csv_validator_spec.rb
Now making use of validation error 'options' containing things like count for I18m messages
This corrects an issue with the address error messages where the page crashed with an error as the interpolation value was not present
```
[ ] Yes
[X] No
```
=> RST 4619 - Now making use of validation error 'options' containing things like count for I18m messages

Gemfile, Gemfile.lock, package.json, yarn.lock
This cannot be merged until the et_gds_design_system gem has been released and the version number had its release candidate removed (i.e. it will be v5.2.1).  But, it can be reviewed ready and the version numbers will be bumped at last minute without further review.
```
[ ] Yes
[ ] No
```
=> (RST-5296) Improve error handling in file uploads
