hmcts/et-pet-et1

- app/forms/address_attributes.rb
- app/forms/claimant_form.rb
- spec/forms/claimant_form_spec.rb
Allow "illegal" postcodes for addresses outside the UK
> I wasn't high when I wrote this.

- app/forms/additional_claimants_upload_form.rb
- app/forms/additional_information_form.rb
- app/mailers/base_mailer.rb
- app/models/claim.rb
- app/presenters/confirmation_presenter.rb
- app/presenters/jadu_xml/file_presenter.rb
- app/services/carrierwave_filename.rb
- app/services/jadu/claim.rb
- app/views/claims/_additional_claimants_upload.html.slim
- app/views/claims/_additional_information.html.slim
- config/initializers/renderers.rb
- spec/features/attaching_a_document_spec.rb
- spec/mailers/base_mailer_spec.rb
- spec/models/claim_spec.rb
- spec/presenters/jadu_xml/file_presenter_spec.rb
- spec/services/carrierwave_filename_spec.rb
- spec/support/files/alt_file.csv
- spec/support/shared_contexts/block_pdf_generation.rb
> Fixes filenames for claim attachments

- app/views/claims/_additional_claimants_upload.html.slim
> updated static path

- spec/factories.rb
- spec/features/claim_xml_generation_spec.rb
> Improves the ACAS examples for the Respondent in the claim XML feature

- app/views/claims/_additional_information.html.slim
- app/views/claims/_additional_respondents.html.slim
- app/views/claims/_claim_details.html.slim
- config/locales/claim_review.en.yml
- config/locales/en.yml
> Copy updates 

- app/forms/employment_form.rb
- spec/forms/employment_form_spec.rb
When entering payment amounts validate presence of the frequency
component
> Employment form changes

- app/views/cookies/markdown/general.md
- app/views/guides/markdown/acas_early_conciliation.md
- app/views/guides/markdown/fees_and_payment_working_out_your_fee.md
- app/views/guides/markdown/reducing_fees.md
- app/views/guides/markdown/time_limits.md
- app/views/shared/_aside.html.slim
- app/views/terms/markdown/privacy_policy_data_storage.md
- config/locales/claim_confirmation.en.yml
fixes #560 pivotal https://www.pivotaltracker.com/story/show/86143454
> external links have correct icons

- app/assets/javascripts/application.js
- app/assets/javascripts/modules/moj.ga-tracking.js
- app/views/claims/_additional_claimants.html.slim
- app/views/claims/_additional_information.html.slim
- app/views/claims/_additional_respondents.html.slim
- app/views/claims/_claim_details.html.slim
- app/views/claims/_claim_type.html.slim
- app/views/claims/_claimant.html.slim
- app/views/claims/_employment.html.slim
- app/views/claims/_representative.html.slim
- app/views/claims/_respondent.slim
- app/views/claims/_your_fee.html.slim
- app/views/claims/new.html.slim
- app/views/layouts/application.html.slim
- app/views/shared/_aside.html.slim
- app/views/user_sessions/reminder.html.slim
- config/locales/en.yml
The module does:
- Regular page views
- Custom Event tracking
- Virtual page views tracking
@Demwunz this is ready for review. Will need to run all this past @TrentDSD before it is merged.
There might be changes - to make some events into page views for example.
See the brief from @TrentDSD  here:
https://docs.google.com/a/digital.justice.gov.uk/document/d/1mf-T9q6xljrkdxF_iqaWYeaqj2DFLYiR-bpRIdjAZHM/edit
> Google analytics tracking module

- app/assets/javascripts/modules/moj.remove-multiple.js
fixes #562 pivotal https://www.pivotaltracker.com/story/show/84666416
> scroll to new additional item on page load

- .env
- app/forms/additional_claimants_upload_form.rb
- app/forms/additional_information_form.rb
- app/presenters/additional_information_presenter.rb
- app/presenters/claimant_csv_presenter.rb
- app/uploaders/attachment_uploader.rb
- app/uploaders/base_uploader.rb
- app/uploaders/claim_pdf_uploader.rb
- app/validators/content_type_validator.rb
- config/initializers/carrierwave.rb
- spec/controllers/pdfs_controller_spec.rb
- spec/features/create_claim_applications_spec.rb
- spec/features/multiple_respondents_spec.rb
- spec/forms/additional_claimants_upload_form_spec.rb
- spec/rails_helper.rb
- spec/support/form_methods.rb
~~- [ ] Check carrierwave default store_dir path. Base uploader might not be required.~~
> Mock AWS S3 in dev & test

- public/404.html
- public/422.html
- public/500.html
- public/503.html
Error pages for 404, 422, 500, and 503 HTTP errors
URLs:
http://0.0.0.0:3000/404.html
http://0.0.0.0:3000/422.html
http://0.0.0.0:3000/500.html
http://0.0.0.0:3000/503.html
@Demwunz There is an issue with the footer not being on the bottom of the page. Can you take a look? Also maybe we can remove the references to the JS too for these pages?
> Static error pages

- app/assets/stylesheets/elements/_buttons.scss
- app/views/shared/_aside.html.slim
> fixed #583

- app/assets/javascripts/modules/moj.ga-tracking.js
> fixed js blocking error

- docker/rails/logstash-conf.sh
This will ship the sneakers log to logstash but remove the heartbeats which occur every 0.4s!
> Ship sneakers.log and strip heartbeats

- app/services/jadu/api/request.rb
- config/initializers/amqp.rb
- docker/rails/sneakers.service
@dan-palmer happy with this? I've set some sane defaults and made it possible to pass in ENV vars to overwrite.
> Fix worker timeouts

- config/routes.rb
Would like a test here but couldn't find how to test routes with IP constraints. Will have to look into this at a later date.
> Fix up IP address for admin routes [ci skip]

- app/presenters/confirmation_email_presenter.rb
- app/presenters/confirmation_presenter.rb
- app/views/base_mailer/access_details_email.en.text.erb
- app/views/base_mailer/confirmation_email.text.erb
- config/environments/production.rb
- config/environments/test.rb
- config/locales/mailers.en.yml
- spec/features/create_claim_applications_spec.rb
- spec/features/save_and_return_spec.rb
- spec/forms/additional_claimants_form/additional_claimant_spec.rb
- spec/forms/additional_respondents_form/additional_respondent_spec.rb
- spec/forms/claimant_form_spec.rb
- spec/forms/representative_form_spec.rb
- spec/forms/respondent_form_spec.rb
- spec/mailer_previews/confirmation_email_preview.rb
- spec/mailers/base_mailer_spec.rb
- spec/support/mail_matchers.rb
Emails:
access_details_email
```
Claim number: X7V2-PMCC
You’ve started a claim to an employment tribunal. To return to your claim you’ll
need your claim number (above), and memorable word.
Clicking on the links below will not work. Please copy and paste URLs into your
browser.
Complete claim: http://localhost:3000/apply/session/new
You’ll receive a confirmation email once you’ve submitted your claim.
Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment
If you’re not sure whether an email is from the Ministry of Justice then:
- do not reply or click any links
- forward it to security@digital.justice.gov.uk
```
group_payment_with_remission
```
Claim number: T96M-M6XF
Barrington Wrigglesworth
Thank you for submitting your claim to an employment tribunal.
What happens …
```
> Plain text emails

- app/assets/stylesheets/_helpers.scss
- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/_shame.scss
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/elements/_mobile-nav.scss
- app/assets/stylesheets/forms/_form-chunky-labels.scss
- app/assets/stylesheets/forms/_form-prefixes.scss
> fixed mobile spacing & clearfix mixin

- config/environments/development.rb
- public/404.html
- public/422.html
- public/500.html
- public/503.html
@stevegraham @dan-palmer this changes how the assets are served in dev. Think this is the only way that we can include static pages that work in both dev and prod.
> Fix error page assets.

- config/initializers/amqp.rb
- lib/tasks/sneakers.rake
* Pool connections to DB from workers.
* Close connection after work is done.
> Fix sneakers AR connections

- app/services/jadu/api/new_claim.rb
- app/services/jadu/api/parsed_response.rb
- spec/services/jadu/api/parsed_response_spec.rb
- spec/services/jadu/claim_spec.rb
> ParsedResponse values_at addition

- config/locales/en.yml
> Update copy to use memorable word

- app/assets/stylesheets/_shame.scss
- app/assets/stylesheets/elements/_tables.scss
- app/views/claim_reviews/_collection.html.slim
- app/views/claim_reviews/_item.html.slim
- app/views/claim_reviews/show.html.slim
> changed review list to tables

- app/models/claim.rb
- app/presenters/jadu_xml/claim_presenter.rb
- app/presenters/pdf_form/claim_presenter.rb
- spec/features/claim_xml_generation_spec.rb
- spec/models/claim_spec.rb
- spec/presenters/pdf_form/claim_presenter_spec.rb
- spec/support/et1_pdf_example.yml
> Check the claim type in pdf & populate the number of claimants field

- app/presenters/claim_type_presenter.rb
- config/locales/en.yml
- spec/presenters/claim_type_presenter_spec.rb
> Appends ‘discrimination’ to discrimination claim types on the review page

- app/views/claims/_your_fee.html.slim
- config/locales/en.yml
> fixes #699

- app/forms/claimant_form.rb
- config/locales/en.yml
- spec/forms/claimant_form_spec.rb
> Validates the claimants email address if it is present

- config/initializers/amqp.rb
- config/unicorn.rb
- docker/rails/unicorn.service
@dan-palmer just a small change here so that I can set the number of workers through env vars.
To solve #731
> Make workers configurable

- app/views/base_mailer/confirmation_email.html.slim
- app/views/base_mailer/confirmation_email.text.erb
- app/views/claim_confirmations/show.html.slim
> changed feedback links

- app/assets/stylesheets/_shame.scss
- app/controllers/guides_controller.rb
- app/views/guides/markdown/acas_early_conciliation.md
- app/views/guides/markdown/acas_early_conciliation_exceptions.md
- app/views/guides/markdown/fees_and_payment.md
- app/views/guides/markdown/fees_and_payment_paying_your_fee.md
- app/views/guides/markdown/fees_and_payment_working_out_your_fee.md
- app/views/guides/markdown/reducing_fees.md
- app/views/guides/markdown/time_limits.md
- app/views/guides/markdown/writing_your_claim_statement.md
- app/views/guides/show.html.slim
- config/locales/en.yml
- spec/features/guide_spec.rb
Fixes #720 
Fixes #692 
lord @michaelelwin decrees the changes are fit and must go live.
> Guide Changes + Back To Form From Guide Helper

- app/presenters/confirmation_email_presenter.rb
- app/views/base_mailer/confirmation_email.html.slim
- app/views/base_mailer/confirmation_email.text.erb
- app/views/base_mailer/shared/_button_fee_remission.html.slim
- app/views/claim_confirmations/show.html.slim
- app/views/guides/markdown/reducing_fees.md
- config/locales/claim_confirmation.en.yml
- config/locales/mailers.en.yml
- spec/features/confirmation_page_spec.rb
- spec/features/create_claim_applications_spec.rb
- spec/mailers/base_mailer_spec.rb
- spec/presenters/confirmation_email_presenter_spec.rb
- spec/support/mail_matchers.rb
> Updates confirmation page/emails remission texts

- app/views/base_mailer/confirmation_email.html.slim
- app/views/base_mailer/confirmation_email.text.erb
- app/views/claim_confirmations/show.html.slim
- app/views/guides/markdown/reducing_fees.md
- config/locales/claim_confirmation.en.yml
- config/locales/mailers.en.yml
- spec/features/confirmation_page_spec.rb
- spec/mailers/base_mailer_spec.rb
- Some wording changes.
- Tests fee remission guide link exists.
* * *
* * *
* * *
@michaelelwin @milror00 @Demwunz
> Remission Copy Changes

- app/views/guides/markdown/fees_and_payment_working_out_your_fee.md
- app/views/terms/markdown/general.md
- config/locales/claim_confirmation.en.yml
- config/locales/claim_review.en.yml
- config/locales/en.yml
- config/locales/mailers.en.yml
- config/locales/simple_form.en.yml
- spec/features/attaching_a_document_spec.rb
- spec/features/your_fee_page_spec.rb
- spec/forms/additional_claimants_form/additional_claimant_spec.rb
- spec/forms/additional_respondents_form/additional_respondent_spec.rb
- spec/forms/claimant_form_spec.rb
- spec/forms/representative_form_spec.rb
- spec/forms/respondent_form_spec.rb
- spec/services/additional_claimants_csv/validator_spec.rb
> Removes 'Please' from all error messages

- app/views/claims/_claimant.html.slim
- config/locales/en.yml
as per user testing feedback with the blind gentleman
> added lables where necessary - removed legends elsewhere

- app/assets/stylesheets/forms/_form-chunky-labels.scss
- app/assets/stylesheets/forms/_form-prefixes.scss
- app/assets/stylesheets/mq/_mobile.scss
addresses an issue where slim labels were messed up due to a change elsewhere in sass templates.
> Slim Label Fix

- app/admin/claim.rb
- app/admin/presenters/payment_status.rb
- spec/admin/presenters/payment_status_spec.rb
- spec/factories.rb
- spec/features/admin_panel/admin_index_feature_spec.rb
- spec/features/admin_panel/admin_show_feature_spec.rb
- spec/features/claim_xml_generation_spec.rb
> Adds ability to download text areas as txt files in the admin GUI

- public/500.html
> fixes #781

- app/views/claims/_your_fee.html.slim
- app/views/guides/markdown/reducing_fees.md
- config/locales/claim_confirmation.en.yml
- config/locales/mailers.en.yml
- spec/features/confirmation_page_spec.rb
- spec/mailers/base_mailer_spec.rb
Updates the external links for the fee remission form guide & fee remission form pdf's.
> Fee help pdf link updates

- app/models/claim.rb
- app/validators/respondents_count_validator.rb
- app/views/claims/_additional_respondents.html.slim
- config/application.rb
- config/locales/en.yml
- spec/features/barclaycard_payment_template_spec.rb
- spec/features/multiple_claimants_spec.rb
- spec/models/claim_spec.rb
Card: https://trello.com/c/eU5MXXxO
> Respondents number bug

- Dockerfile
- README.md
- app/controllers/guides_controller.rb
- app/views/guides/markdown/payments_from_ni_fund.md
- config/environments/local.rb
- config/locales/en.yml
Card: https://trello.com/c/pLvFLQxw
> Change text to indicate fee exempt claims

- Gemfile.lock
- app/assets/javascripts/modules/moj.remove-multiple.js
- app/controllers/guides_controller.rb
- app/forms/claim_type_form.rb
- app/models/claim.rb
- app/presenters/jadu_xml/claimant_presenter.rb
- app/views/claims/_claim_details.html.slim
- app/views/claims/_claim_type.html.slim
- app/views/guides/markdown/acas_early_conciliation_exceptions.md
- app/views/guides/markdown/fees_and_payment_working_out_your_fee.md
- app/views/guides/markdown/reducing_fees.md
- config/locales/en.yml
- db/migrate/20161013151741_add_is_protective_award_to_claims.rb
- db/schema.rb
- spec/factories.rb
- spec/features/attaching_a_document_spec.rb
- spec/features/claim_xml_generation_spec.rb
- spec/features/guide_spec.rb
- spec/forms/claim_type_form_spec.rb
- spec/models/claim_spec.rb
- spec/presenters/jadu_xml/claimant_presenter_spec.rb
- spec/services/claim_fee_calculator_spec.rb
I've batched together a list of smaller ET amends - mainly involving copy/link changes.
> ET text amends

- Gemfile
- Gemfile.lock
- config/initializers/raven.rb
Associated changes made in atet-deploy
> Add sentry to ET

- app/admin/claim.rb
Allow filtering on fee group reference and application reference
and display the submission state on the admin detail page
> Improve the admin section

- config/locales/en.yml
- spec/forms/claim_type_form_spec.rb
@lgarvey it's just a copy change.
> Updating error message for claim_type page.

- app/controllers/guides_controller.rb
- config/locales/en.yml
Belongs to this. https://trello.com/c/Lh3N8ry7/216-revert-sensitive-fees-review-info
> Reverting sensitive - Fees Review Info

- config/locales/en.yml
- spec/forms/claim_type_form_spec.rb
> Fixing typo

- spec/features/multiple_claimants_csv_spec.rb
- spec/support/files/group-claim.csv
https://triadmoj.atlassian.net/browse/RST-39
CSV upload is using validation from additional_claimant form so I just wrote tests.
@lgarvey take a look pls :)
> Writing tests for group claims CSV upload.

- app/views/claims/_personal_details.html.slim
- spec/features/multiple_claimants_spec.rb
https://triadmoj.atlassian.net/browse/RST-30
Displaying DoB helper hint on group claim.
> Adding help hint for group claims DOB.

- config/locales/en.yml
- spec/features/attaching_a_document_spec.rb
- spec/features/multiple_claimants_spec.rb
- spec/services/additional_claimants_csv/validator_spec.rb
https://triadmoj.atlassian.net/browse/RST-31
Updating validation error message for DoB.
> Adding correct DOB format validation message.

- app/forms/address_attributes.rb
- app/forms/respondent_form.rb
- app/presenters/claim_presenter.rb
- app/presenters/confirmation_email_addresses_presenter.rb
- app/services/additional_claimants_csv/base_csv.rb
- app/services/additional_claimants_csv/error_conversion.rb
- app/services/claim_fee_calculator.rb
- app/services/claim_fee_calculator/calculation.rb
- app/services/claim_fee_calculator/remission_calculator.rb
- app/services/jadu/claim.rb
- app/services/payment_gateway/request.rb
- app/services/payment_gateway/response.rb
- app/services/pdf_form_builder.rb
- spec/forms/additional_claimants_form_spec.rb
Refactoring and removing some TODO comments. Mostly it's on inheritance from Struct where it's not needed.
> Fist part of removing Struct as a parent class.

- run.sh
**Update run.sh to support migrate and create db**
> Update run.sh to support migrate and create db

- app/views/refunds/_applicant.html.slim
- config/locales/refunds.yml
- features/refund_validations_applicant.feature
Added link to paper refund form for when users have said their name has changed
Nice simple one this time :-)
> Added link to paper refund form for when users have said their name has changed

- app/assets/stylesheets/pages/refunds/refunds-fees.scss
- config/locales/refunds.yml
- features/step_definitions/refunds/fees_steps.rb
This PR makes some very small styling changes and changes to the default selection wording in the fees page to make it look less cluttered
> Minor tweaks to styling and default selection in fees page

- config/locales/refunds.yml
This PR is literally a trivial text change in the refunds.yml file - nothing else
> Minor text change

- .rspec_parallel
- .travis.yml
- Gemfile
- Gemfile.lock
- config/database.yml
- features/support/capybara_driver_helper.rb
This PR uses the parallel tests gem to allow travis to split the tests between 2 parallel processes  using the same single VM
> Parallel tests

- config/locales/refunds.yml
Simple text change to state 15 working days instead of just 14 days for the refund to be processed
> Simple text change to state 15 working days (RST-648)

- app/forms/refunds/profile_selection_form.rb
- config/locales/refunds.yml
- features/refund_end_to_end.feature
- features/step_definitions/refunds/new_refund_steps.rb
- features/support/page_objects/refund/profile_selection_page.rb
- spec/forms/refunds/profile_selection_form_spec.rb
Simple text changes to profile selection page as requested
> Simple text changes to profile selection page as requested (RST-645)

- app/forms/refunds/applicant_form.rb
- config/locales/refunds.yml
- features/step_definitions/refunds/applicant_steps.rb
- features/step_definitions/refunds/setup_steps.rb
- spec/forms/refunds/applicant_form_spec.rb
- spec/spec_helper.rb
- spec/support/files/file-l_o_l.biz._v1_.csv
- spec/support/files/file-l_o_l.biz._v1_.rtf
The applicant address now must have the town/city filled in - it is no longer optional
> RST-838 The applicant address now must have the town/city filled in 

- config/routes.rb
This PR whitelists Liberata's IP.
> Allow Liberata to access the Admin panel

- app/views/terms/markdown/applicable_law.md
Forget to update Applicable law paragraph.
> Updating Applicable Law content.

- config/locales/cy/cy.yml
- config/locales/en/en.yml
Just updating a copy in the header.
> Removing 'This is a new service' from header

- app/services/et_api.rb
Minor improvement to API calling code to provide better errors
> Minor improvement to API calling code to provide better errors

- config/environments/local.rb
Local logging will now log to STDOUT if configured
> Local logging will now log to STDOUT if configured

- Gemfile
- Gemfile.lock
Configured to use azure_env_secrets ready for azure
> RST-1751 ET1 (Azure) - Configure to use the azure_env_secrets gem

- README.md
Should help my fellow morons and I to get this working locally.
> Add Working Build Info to README

- config/routes.rb
Added reform VPN IP address to route restrictions for admin and sidekiq
> Added reform VPN IP address to route restrictions for admin and sidekiq

- config/initializers/sidekiq.rb
- run.sh
- run_sidekiq.sh
This PR changes the run.sh and run_sidekiq.sh scripts to be azure compatible and full system compatible
It also allows sidekiq to be configured easier (for full system)
> run.sh can now be used to run locally (full system)

- Dockerfile
- azure-pipelines.yml
> Adding Azure Pipelines Devops functionality

- app/views/layouts/application.html.slim
Add CSRF token to ET1
```
[ ] Yes
[x] No
```
> Add CSRF token

- README.md
- azure-pipelines.yml
Enbabling applicaiton testing.
Setting up conditional on image build and asset deploy jobs to develop branch only
Adding ADO build badge
```
[ ] Yes
[x] No
```
> updating Devops pipelines and ADO build badge

- Dockerfile
- azure-pipelines.yml
> adding ping.json fix for ADO and cleanup step

- azure-pipelines.yml
> adding manual build support for pipelines

- azure-pipelines.yml
- docker-compose-test.yml
- docker-compose.yml
> Fix to address multiple jobs error in ADO

- config/locales/cy/claim_confirmation.cy.yml
RST-2008
This PR changes the welsh confirmation messages only
```
[ ] Yes
[X] No
```
> Added welsh confirmation messages

- app/forms/additional_claimants_form/additional_claimant.rb
- app/forms/claimant_form.rb
- app/helpers/claim_reviews_helper.rb
- app/presenters/pdf_form/base_delegator.rb
- app/presenters/pdf_form/primary_claimant_presenter.rb
- app/views/claim_reviews/_claimant.html.slim
RST-2126
This PR enables the title and gender fields to be optional as requested in RST-2126
```
[ ] Yes
[X] No
```
> RST-2126 Make fields non mandatory

- azure-pipelines.yml
adding volume removal flag to the test stage
```
[ ] Yes
[x] No
```
> adding volume removal flag to the test stage

- config/environments/development.rb
Non functional change - just a config update for developers - doesnt affect production
```
[ ] Yes
[ ] No
```
> development environment now has config.hosts.clear

- azure-pipelines.yml
remove deployment to blob storage. This is no longer needed as assets are hosted internally 
```
[ ] Yes
[x] No
```
> remove deployment to blob storage

- config/routes.rb
I took off the GDS link in the routes.
```
[ ] Yes
[ X] No
```
> RST-1902 Took off the GDS link

- app/forms/employment_form.rb
- azure-pipelines.yml
- config/database.yml
- docker-compose-test.yml
- features/support/webmock.rb
- spec/forms/employment_form_spec.rb
RST-2466
This PR ensures that the date validation in the employment form all works when partial dates are given
```
[ ] Yes
[X] No
```
> RST-2466 Date error handling fixed

- azure-pipelines.yml
- docker-compose-test.yml
RST-2468
RST-2468 Test image being cached on the host
```
[ ] Yes
[x] No
```
> RST-2468 Test image being cached on the host

- config/locales/en/cookies.en.yml
Content for Cookies has been changed
```
[ ] Yes
[X ] No
```
> RST-1614-CookiesPolicy

- config/locales/en/cookies.en.yml
I took off extra parentheses.
```
[ ] Yes
[X ] No
```
> RST-1614 Cookie Fix

- app/views/diversities/_age_caring.html.slim
- app/views/diversities/_identity.html.slim
I took off the optional next to the question for the diversity questionnaire.
```
[ ] Yes
[ X] No
```
> RST-2261-Diversity

- app/views/claim_confirmations/show.html.slim
- config/locales/cy/claim_confirmation.cy.yml
- config/locales/en/claim_confirmation.en.yml
Changes made for the COVID-19 on the confirmation page.
```
[ ] Yes
[X ] No
```
> RST-2549-COVID19

- app/controllers/claim_reviews_controller.rb
- app/views/claim_confirmations/show.html.slim
- spec/support/webmock.rb
https://tools.hmcts.net/jira/browse/RST-2009
This PR changes the final submission page to show the fee group reference instead of the application reference.
```
[ ] Yes
[X] No
```
> RST-2009 Change claim number on ET1 submission page

- Gemfile
- Gemfile.lock
- app/controllers/feedback_controller.rb
- app/views/feedback/new.html.slim
- spec/controllers/feedback_controller_spec.rb
- spec/features/feedback_spec.rb
Honey pot CAPTCHA added to the feedback form
```
[ ] Yes
[ X] No
```
> RST-2532 Added CAPTCHA for feedback

- Gemfile.lock
- app/forms/claimant_form.rb
- app/views/claims/_claimant.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
RST-2607
Remainder of the claimants page done after using freds radio button collection
```
[ ] Yes
[ ] No
```
> RST-2607 Fixed remainder of claimants details page

- config/locales/cy/cy.yml
- config/locales/en/en.yml
Changed the content for the amendment.
```
[ ] Yes
[X ] No
```
> RST-2693 Content amendment changed

- config/locales/cy/terms.cy.yml
- config/locales/en/terms.en.yml
The email addresses for the Privacy Policy has been changed.
```
[ ] Yes
[ X] No
```
> RST-2755 Privacy Policy email address changed

- Gemfile.lock
- app/controllers/multiple_claimants_controller.rb
- app/controllers/multiple_respondents_controller.rb
- app/forms/additional_claimants_form.rb
- app/forms/additional_respondents_form.rb
- app/forms/base_form.rb
- app/models/claim.rb
- app/views/claims/_additional_respondents.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- config/routes.rb
- db/migrate/20200803155627_add_has_multiple_respondents_to_claims.rb
- db/migrate/20200803155659_migrate_multiple_respondents.rb
- db/migrate/20200804051237_add_no_acas_number_to_respondents.rb
- db/migrate/20200804051338_migrate_no_acas_number_in_respondents.rb
- db/schema.rb
- spec/factories/ui/respondents_ui_factory.rb
- spec/factories/ui/secondary_respondents_ui_factory.rb
- spec/features/create_claim_applications_spec.rb
- spec/features/multiple_claimants_spec.rb
- spec/features/multiple_respondents_spec.rb
- spec/forms/additional_respondents_form_spec.rb
- spec/support/form_methods.rb
- spec/support/messaging/en.yml
- spec/support/page_object_helpers.rb
- spec/support/page_objects/additional_respondents_page.rb
- spec/support/page_objects/group_claims_page.rb
> RST-2798 (ET1) Component Upgrade - Multiple Respondents Page

- app/forms/claimant_form.rb
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- spec/forms/claimant_form_spec.rb
> hotfix/video-validation Fixed incorrect validator on video question

- config/locales/cy/devise.cy.yml
- config/locales/en/devise.en.yml
- spec/support/page_objects/return_to_your_claim_page.rb
Changed error and translation
```
[ ] Yes
[X ] No
```
> RST-2668 Error added with translation

- app/views/claim_confirmations/show.html.slim
- config/locales/cy/claim_confirmation.cy.yml
- config/locales/en/claim_confirmation.en.yml
Added content for the experience issue on the email going into the spam.
```
[ ] Yes
[ X] No
```
> RST-2891 Added content for experience issue

- config/locales/cy/devise.cy.yml
- config/locales/en/devise.en.yml
Changed some translation.
```
[ ] Yes
[X ] No
```
> RST-2668 Change translation content

- db/migrate/20201005105200_migrate_saved_claims_again.rb
- db/schema.rb
> hotfix-data-migration - Issue with old save and return data

- app/views/claim_confirmations/show.html.slim
- config/locales/cy/claim_confirmation.cy.yml
- config/locales/en/claim_confirmation.en.yml
This reverts commit 7825964a
```
[ ] Yes
[ ] No
```
> Revert "RST-2891 Added content for experience issue (#1286)"

- config/locales/cy/cy.yml
- config/locales/en/en.yml
RST-2996 Changed file size limit for csv files
```
[ ] Yes
[X] No
```
> RST-2996 Changed file size limit for csv files

- Gemfile.lock
- app/views/claims/_additional_claimants_upload.html.slim
- app/views/claims/_additional_respondents.html.slim
- app/views/claims/_address.html.slim
- app/views/claims/_application_number.html.slim
- app/views/claims/_claimant.html.slim
- app/views/claims/_personal_details.html.slim
- app/views/claims/_respondent.slim
RST-3030 Upgraded to latest form builder
```
[X] Yes
[ ] No
```
> RST-3030 Upgraded to latest form builder

- Gemfile.lock
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- spec/factories/ui/claimant_ui_factory.rb
- spec/features/claimant_spec.rb
Rst 3023 Re work video question to work with new gds
```
[ ] Yes
[ ] No
```
> Rst 3023 Re work video question to work with new gds

- app/views/claims/_additional_information.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- spec/features/quick_edit_spec.rb
> RST-2800 Additional information page now using new gds

- app/views/claims/_claim_outcome.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- spec/features/quick_edit_spec.rb
> Rst 2801 - Claim outcome page now using GDS components

- app/assets/csv/group-claims-template-cy.csv
- app/assets/csv/group-claims-template.csv
- app/assets/javascripts/active_admin.js
- app/forms/employment_form.rb
- app/views/claim_reviews/_employment.html.slim
- config/locales/en/en.yml
- spec/factories/ui/employment_ui_factory.rb
- spec/features/create_claim_applications_spec.rb
- spec/forms/employment_form_spec.rb
- spec/support/form_methods.rb
- spec/support/messaging/en.yml
- spec/support/page_objects/employment_details_page.rb
- spec/support/shared_examples/date.rb
Improves tests to allow the suite to get further than the employment page
```
[ ] Yes
[X] No
```
> RST-2611 Sorted testing stuff for the employment page

- Gemfile
- Gemfile.lock
- app/views/claims/_claim_outcome.html.slim
- spec/factories/ui/claim_outcome_ui_factory.rb
- spec/features/create_claim_applications_spec.rb
- spec/support/form_methods.rb
- spec/support/messaging/en.yml
- spec/support/page_objects/claim_outcome_page.rb
Claim outcome page now using gds
```
[ ] Yes
[ ] No
```
> RST-3109 Claim outcome page done

- app/views/claim_reviews/_additional_claimants.html.slim
- app/views/claim_reviews/_additional_claimants_csv.html.slim
- app/views/claim_reviews/_additional_respondents.html.slim
- app/views/claim_reviews/_answer.html.slim
- app/views/claim_reviews/_answer_address.html.slim
- app/views/claim_reviews/_answer_temp.html.slim
- app/views/claim_reviews/_answer_yes_no.html.slim
- app/views/claim_reviews/_email_addresses.html.slim
- app/views/claim_reviews/_item.html.slim
- app/views/claim_reviews/show.html.slim
- spec/factories/ui/claimant_ui_factory.rb
- spec/factories/ui/representative_ui_factory.rb
- spec/features/create_claim_applications_spec.rb
- spec/features/guide_spec.rb
- spec/features/multiple_claimants_respondents_on_review_page_spec.rb
- spec/features/quick_edit_spec.rb
- spec/support/capybara_selectors/et1_review_additional_claimant_labelled.rb
- spec/support/capybara_selectors/et1_review_question_labelled.rb
- spec/support/capybara_selectors/et1_review_section_labelled.rb
- spec/support/messaging/en.yml
- spec/support/page_object_helpers.rb
- spec/support/page_objects/review_page.rb
RST-3024 Review page now using new gds.
```
[ ] Yes
[X] No
```
> RST-3024 Review page now using new gds.

- azure-pipelines.yml
> Updated pool to run push and deploy tasks

- app/views/claims/new.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
RST-2605 Entrance page now using new gds styling
```
[ ] Yes
[X] No
```
> RST-2605 Entrance page now using new gds styling

- app/views/guides/_acas_early_conciliation.html.slim
- config/locales/cy/guides.cy.yml
- config/locales/en/guides.en.yml
- spec/support/webmock.rb
https://tools.hmcts.net/jira/browse/RST-3089
RST-3089 Amended wording on guide page for acas opening hours
```
[ ] Yes
[X] No
```
> RST-3089 Amended wording on guide page for acas opening hours

- app/views/save_and_return/passwords/edit.html.slim
- app/views/save_and_return/passwords/new.html.slim
- app/views/save_and_return/registrations/new.html.slim
- app/views/save_and_return/sessions/new.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
Save and return feature changed for the GDS upgrade
```
[ ] Yes
[X] No
```
> RST-2606 GDS upgrade for save and return feature

- config/locales/cy/terms.cy.yml
- config/locales/en/terms.en.yml
Changed content on the Terms and conditions page regarding the data stored.
```
[ ] Yes
[ X] No
```
> RST-3060 Content changes

- Gemfile.lock
- app/views/diversities/_age_caring.html.slim
- app/views/diversities/_claim_type.html.slim
- app/views/diversities/_confirmation.html.slim
- app/views/diversities/_disability.html.slim
- app/views/diversities/_ethnicity.html.slim
- app/views/diversities/_identity.html.slim
- app/views/diversities/_pregnancy.html.slim
- app/views/diversities/_relationship.html.slim
- app/views/diversities/_religion.html.slim
- app/views/diversities/_review.html.slim
- app/views/diversities/index.html.slim
- app/views/diversities/show.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- package.json
- yarn.lock
Upgraded the diversity questionnaire with the GDS component.
```
[ ] Yes
[X] No
```
> Rst 2803 - Diversity

- app/assets/csv/group-claims-template-cy.csv
- app/assets/csv/group-claims-template.csv
- app/javascript/packs/application.js
- app/javascript/packs/components/SessionPrompt.js
- app/javascript/packs/stylesheets/application.scss
- app/javascript/packs/stylesheets/session_prompt.scss
- app/views/layouts/application.html.slim
- app/views/shared/_session_prompt.html.slim
- spec/features/create_claim_applications_spec.rb
- spec/support/page_objects/base_page.rb
This PR adds the timeout functionality 
```
[ ] Yes
[X] No
```
> Rst 3026 Timeout functionality

- app/forms/address_attributes.rb
- app/forms/claimant_form.rb
- app/forms/respondent_form.rb
- spec/support/shared_examples/postcode_validation.rb
> RST-3221 Disabled ccd post code validator temporarily

- app/forms/respondent_form.rb
- app/validators/ccd_acas_exemption_reason_validator.rb
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- spec/validators/ccd_acas_exemption_reason_validator_spec.rb
Added the ccd_acas_exemption_reason validation with spec and validator.
```
[ ] Yes
[ X] No
```
> RST-3153 ccd acas

- app/forms/address_attributes.rb
- app/validators/ccd_address_validator.rb
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- spec/forms/additional_claimants_form/additional_claimant_spec.rb
- spec/forms/additional_respondents_form/additional_respondent_spec.rb
- spec/forms/claimant_form_spec.rb
- spec/forms/representative_form_spec.rb
- spec/forms/respondent_form_spec.rb
- spec/services/additional_claimants_csv/validator_spec.rb
- spec/validators/ccd_address_validator_spec.rb
Added test and validator for the address field 
```
[ ] Yes
[X] No
```
> RST-3153 ccd address fields

- config/locales/cy/cy.yml
- config/locales/en/en.yml
The content for the cookie banner has been changed.
```
[ ] Yes
[ X] No
```
> RST-3269-content Changed content for cookie banner

- app/forms/address_attributes.rb
- spec/forms/refunds/applicant_form_spec.rb
https://tools.hmcts.net/jira/browse/RST-3388
RST-3388 Changed max length of address fields to 50
```
[ ] Yes
[X] No
```
> RST-3388 Changed max length of address fields to 50

- app/mailers/application_mailer.rb
- app/mailers/feedback_mailer.rb
- config/application.rb
- spec/support/email_support/email_objects/feedback_email_html.rb
- spec/support/email_support/email_objects/feedback_email_text.rb
> HOTFIX Change mailer sender to work with new sendgrid

- app/javascript/packs/application.js
- app/javascript/packs/csv/group-claims-template-cy.csv
- app/javascript/packs/csv/group-claims-template.csv
- app/views/claims/_additional_claimants_upload.html.slim
- config/locales/cy/cy.yml
- config/locales/en/en.yml
- config/webpacker.yml
RST-3217 group claims template now part of webpacker output
```
[ ] Yes
[X] No
```
> RST-3217 group claims template now part of webpacker output

- app/forms/address_attributes.rb
- spec/forms/respondent_form_spec.rb
> RST-3408 (ET1) Validation still incorrect length for some fields

- spec/support/capybara_selectors/flash_message_with_text.rb
> RST-3226 Fixed test issue with session reloaded message in refunds

- app/views/diversities/_identity.html.slim
Removed two questions from the Diversity questionnaire
```
[ ] Yes
[ X] No
```
> RST-3422 Diversity questionnaire

- spec/features/create_claim_applications_spec.rb
- spec/support/refunds_steps/fees_steps.rb
> Rst 3404 - Fixed refund specs

- app/views/claim_reviews/_additional_claimants.html.slim
- app/views/claim_reviews/_additional_respondents.html.slim
- package-lock.json
> Rst 3663 - Fix for invalid HTML in review page (gds component upgrade)

- Dockerfile.test
- app/javascript/packs/stylesheets/application.scss
- app/javascript/packs/stylesheets/form.scss
- app/views/claims/new.html.slim
> Rst 2039 - Return to claim link now a button

- app/views/api/claim/_build_claim.json.jbuilder
- spec/services/submit_claim_to_api_service_spec.rb
- spec/support/api_support/json_objects/v2/build_claim_json_object.rb
Changed to PDF template to use the Version 3 
```
[ ] Yes
[ X] No
```
> RST-3691 Changed the PDF version used

- Gemfile
- Gemfile.lock
- app/views/claim_reviews/_claimant.html.slim
- app/views/claim_reviews/_error_header.html.slim
- app/views/shared/_error_notification.html.slim
- config/environments/development.rb
RST-3744
Fixed issue with review page (GDS upgrade)
```
[ ] Yes
[X] No
```
> Rst 3744 - Fixed issue with review page (GDS upgrade)

- app/views/diversities/_review.html.slim
- config/locales/cy/diversities/diversity.cy.yml
- config/locales/en/diversities/diversity.en.yml
Changed the edit link for the Diversity Questionnaire to point the page it is Editing
```
[ ] Yes
[ X] No
```
> RST-2055-diversity

- app/views/diversities/_disability.html.slim
- app/views/diversities/_pregnancy.html.slim
- app/views/diversities/_review.html.slim
- config/locales/cy/diversities/diversity.cy.yml
- config/locales/en/diversities/diversity.en.yml
All links on the review page have been changed, missing translation also done. 
```
[ ] Yes
[ X] No
```
> RST-3779-links

- db/migrate/20200618060830_migrate_multiple_claimants.rb
- db/migrate/20200803155659_migrate_multiple_respondents.rb
- db/schema.rb
> RST-3858 Fixed problematic migrations - very slow

- app/javascript/packs/stylesheets/application.scss
- app/javascript/packs/stylesheets/multiple_respondents_page.scss
- app/views/claim_confirmations/show.html.slim
- app/views/claims/_additional_respondents.html.slim
- app/views/diversities/_review.html.slim
- app/views/layouts/diversities/application.html.slim
- app/views/shared/_aside.html.slim
- config/locales/cy/et1/claim_review.cy.yml
- config/locales/en/et1/claim_review.en.yml
RST-3781
Various accessibility issues - generally missing classes on anchor tags
```
[ ] Yes
[X] No
```
> RST-3781 ET1 - [Level AA] Accessibility fixes

- app/views/diversities/_review.html.slim
> RST-3781 Ethnic type link now govuk link

- app/services/submit_claim_to_api_service.rb
> RST-3897 Claim submitted_at is no longer overwritten on submission.

- app/forms/form_collection_proxy.rb
- spec/forms/additional_respondents_form_spec.rb
> RST-3967 Et1 - adding additional claimant error

- app/views/claim_reviews/show.html.slim
- spec/support/webmock.rb
Removed the empty link on the review page.
```
[ ] Yes
[ X] No
```
> RST-3860 Removed empty link

- README.md
- app/controllers/application_controller.rb
- app/views/static_pages/maintenance.html.erb
- config/application.rb
> RST-4218 Add custom maintenance pages to et1, et3 and admin

- config/database.yml
> RST-4279 Quoted all external values in database.yml

- app/controllers/save_and_return/registrations_controller.rb
- spec/features/create_claim_applications_spec.rb
> RST-4264 Allowing session to start at /apply/application-number

- app/models/claim.rb
> RST-4124 - Secondary respondents now appearing in order

- app/javascript/packs/application.js
- yarn.lock
> RST-4363 application.js now loads core-js for polyfills

- Dockerfile.test
- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
Changed version of et_gds_design_system gem for the changes made to the reveal content.
```
[ ] Yes
[X] No
```
> RST-3968 Revisioned Gemfile for reveal content

- app/views/claim_reviews/_answer_no.html.slim
- app/views/claim_reviews/_answer_yes_no.html.slim
- app/views/claim_reviews/_claimant.html.slim
- config/locales/cy/et1/claim_review.cy.yml
- config/locales/en/et1/claim_review.en.yml
- spec/views/claim_reviews/show/review_page_claimant_spec.rb
Added new partial to show the answer No on the show page for Disability and Video hearing questions + Translation 
```
[ ] Yes
[ X] No
```
> RST-4248 Showing claimant detail's answer no for show page

- config/locales/cy/et1/active_model.cy.yml
- config/locales/en/et1/active_model.en.yml
RST-4619
RST-4619 Added I18n messages for new validation errors provided by API for csv file upload
```
[ ] Yes
[X] No
```
> RST-4619 Added I18n messages for new validation errors provided by API for csv file upload

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
> Rst 4686 New file upload system

- Gemfile
- Gemfile.lock
RST-4762
RST-4762 Now using updated version of et_azure_insights which supports sidekiq > 6.2.1
```
[ ] Yes
[ ] No
```
> RST-4762 Now using updated version of et_azure_insights which supports sidekiq > 6.2.1

- .env.test
- Gemfile
- Gemfile.lock
- app/forms/collection_form/resource.rb
- config/environments/production.rb
- config/initializers/sentry.rb
- spec/forms/additional_claimants_form/additional_claimant_spec.rb
> RST-4863 ET1 Sentry

- .vscode/launch.json
- Gemfile
- Gemfile.lock
- app/forms/employment_form.rb
- spec/forms/employment_form_spec.rb
> (RST-4593) ET1 - Notice period details missing from pdf

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
> (RST-5296) Bumped gem versions

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/et-pet-et1/.helmignore
- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.aat.template.yaml
- charts/et-pet-et1/values.preview.template.yaml
- charts/et-pet-et1/values.yaml
This is not the finished article - just an initial merge to get the jenkins file into master so that jenkins can see it
```
[ ] Yes
[X] No
```
> (RST-5651) Initial fairly empty config for jenkins and helm chart

- README.md
> (RST-5651) Readme change to trigger build

- sonar-project.properties
> (RST-5651) Added sonar config

- .gitignore
- Jenkinsfile_CNP
- charts/et-pet-et1/Chart.yaml
- sonar-project.properties
- spec/rails_helper.rb
> (RST-5651) Corrected sonar project name

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-5161) Configured known secrets

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-5651) Configured known secrets

- Jenkinsfile_CNP
- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-5651) Added migration code and wired in api url

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> Fixed issue with api urls

- charts/et-pet-et1/values.aat.template.yaml
- charts/et-pet-et1/values.preview.template.yaml
> (RST-5651) Fixed bug in charts for sidekiq

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-5651) Corrected api url

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-5651) Fixed sending host env var

- app/controllers/cookies_controller.rb
- config/application.rb
- config/environments/production.rb
- config/initializers/session_store.rb
> (RST-5891) Secured cookies

- .env.full_system.production
> (RST-5920) Reduced log level to info in fs environment

- spec/rails_helper.rb
> (RST-5959) Fixed coverage issue

- spec/controllers/cookies_controller_spec.rb
> (RST-5962) Added spec for cookies controller

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-5976) Switch to using new app insights

- config/locales/cy/et1/active_model.cy.yml
- config/locales/en/et1/active_model.en.yml
> (RST-6003) Added missing translations for csv row (too_long validation error)

- .bundler-audit.yml
- Gemfile.lock
> (RST-6189) Upgraded puma to address CVE

- Gemfile
- Gemfile.lock
> (RST-5642) GDS Gem upgraded to use ruby 3.2.2 in tests.

- Dockerfile
- Dockerfile.development
- Gemfile
- Gemfile.lock
- bin/run_full_system
(RST-6212) Development docker image permission issues fixed
> (RST-6212) Full system command now runs invoker instead of foreman.

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (Temp) Disable admin

- Gemfile.lock
> (RST-6286) Upgraded nokogiri (security issue)

- Gemfile
- Gemfile.lock
- app/models/admin_user.rb
- bin/run_full_system
- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
- config/initializers/active_admin.rb
- config/initializers/rack_attack.rb
- config/routes.rb
- db/migrate/20240202071800_devise_create_admin_users.rb
- db/migrate/20240208163140_add_admin_user_with_random_password.rb
- db/schema.rb
- db/seeds.rb
- spec/factories.rb
- spec/features/admin_panel/admin_index_feature_spec.rb
- spec/features/admin_panel/admin_show_feature_spec.rb
- spec/models/admin_user_spec.rb
- spec/support/devise_helpers.rb
> (RST-6262) Add password protection to et1 admin

- charts/et-pet-et1/Chart.yaml
> Bumped chart version to force new release

- app/validators/special_character_validator.rb
- spec/validators/special_character_validator_spec.rb
> (RST-6198) Allow forward slashes in addresses

- app/controllers/application_controller.rb
- db/migrate/20240320062552_add_indexes_to_addresses.rb
- db/schema.rb
- spec/controllers/timeout_sessions_controller_spec.rb
> (RST-6321) Slow db query

- README.md
> Dummy change to readme to force build

- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.yaml
> (RST-6695) Increased startup timeout for running migrations

- app/helpers/dynatrace_helper.rb
- app/views/cookies/edit.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/moj_template.html.erb
- app/views/shared/_dynatrace_script_tag.html.erb
- charts/et-pet-et1/Chart.yaml
- charts/et-pet-et1/values.aat.template.yaml
- charts/et-pet-et1/values.preview.template.yaml
- config/application.rb
- config/locales/cy/et1/cookies.cy.yml
- config/locales/en/et1/cookies.en.yml
- spec/features/dynatrace_spec.rb
- spec/helpers/dynatrace_helper_spec.rb
> (RST-6869) Dynatrace configuration

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RST-7038
> RST-7038 - GovUK Frontend crest logo update
